name: cameoFlowServer
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: bowenchiu <cbh@cameo.tw>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  args: ^1.5.0
  shelf: any
  shelf_static: any
  json_annotation: any
  logging: any
  intl: any
  jsonp: any
  js: any
  shelf_proxy: any

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
