function funcTableDot(lstData) {
  $(document).ready(function () {
    var table = $('#tableDot').removeAttr('width').DataTable({
      stateSave: true,
      destroy: true,
      "scrollX": true,
      "scrollY": true,
      "data": lstData,
      fixedColumns: false,
      columnDefs: [
        {width: 1, targets: 0},
        {width: 1, targets: 1},
        {width: 1, targets: 2},
      ],
      columns: [
        {title: "規劃師"},
        {title: "1G"},
        {title: "1Y"},
        {title: "1R"},
        {title: "2G"},
        {title: "2Y"},
        {title: "2R"},
        {title: "3G"},
        {title: "3Y"},
        {title: "3R"},
        {title: "4G"},
        {title: "4Y"},
        {title: "4R"},
        {title: "5G"},
        {title: "5Y"},
        {title: "5R"},
        {title: "6G"},
        {title: "6Y"},
        {title: "6R"},
        {title: "7G"},
        {title: "7Y"},
        {title: "7R"},
        {title: "8G"},
        {title: "8Y"},
        {title: "8R"},
        {title: "9G"},
        {title: "9Y"},
        {title: "9R"},
        {title: "AG"},
        {title: "AY"},
        {title: "AR"},
        {title: "BG"},
        {title: "BY"},
        {title: "BR"},
        {title: "CG"},
        {title: "CY"},
        {title: "CR"},
        {title: "DG"},
        {title: "DY"},
        {title: "DR"},
        {title: "EG"},
        {title: "EY"},
        {title: "ER"},
        {title: "FG"},
        {title: "FY"},
        {title: "FR"},
      ]
    });
  });
}
